version: '3'
services:
    app:
        build:
            args:
                NODE_ENV: production
            context: .
        env_file: .env.production
        ports:
            - ${PORT:-8215}:${PORT:-8215}