version: '3'
services:
    app:
        env_file:
            - .env
        build:
            context: .
        ports:
            - ${PORT:-8215}:${PORT:-8215}
        environment:
            NODE_ENV: production
